lint:
  stage: build
  script:
    # - pip3 install codespell
    # - sudo apt-get install cmake cpuRHdBD6cB4aekKjUWnD2chMMHSzuYGNqiNl4pLmKBXQ=pcheck clang-format clang-tidy lcov gcovr -y -q
    - cmake -D FORMAT_COMMAND=clang-format -P cmake/lint.cmake
    - cmake -P cmake/spell.cmake

test-job1:
  stage: test
  script:
    - cmake --preset=ci-ubuntu
    - cmake --build build --config Release -j 2
    - cmake --install build --config Release --prefix prefix
    - ./build/test/repo1_gtest --gtest_output="xml:report.xml"
  artifacts:
    when: always
    reports:
      junit: report.xml

coverage:
  stage: test
  script:
    - cmake --preset=ci-coverage
    - cmake --build build/coverage -j 2
    - cd build/coverage && ctest --output-on-failure --no-tests=error -j 2
    - cd ../.. && cmake --build build/coverage -t coverage
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    expire_in: 2 days
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/coverage/coverage.xml